ns_fn <- function(name) {
  getFromNamespace(name, "MPCurver")
}

cavi <- ns_fn("cavi")
do_cavi <- ns_fn("do_cavi")
soft_partition_cavi <- ns_fn("soft_partition_cavi")
soft_two_trajectory_cavi <- ns_fn("soft_two_trajectory_cavi")
soft_two_trajectory_EM <- ns_fn("soft_two_trajectory_EM")
as_mpcurve <- ns_fn("as_mpcurve")
evaluate_partition <- ns_fn("evaluate_partition")
score_features_onefit_cavi <- ns_fn("score_features_onefit_cavi")
partition_features_twofits_cavi <- ns_fn("partition_features_twofits_cavi")
init_m_trajectories_cavi <- ns_fn("init_m_trajectories_cavi")
init_two_trajectories_cavi <- ns_fn("init_two_trajectories_cavi")
forward_two_ordering_partition_csmooth <- ns_fn("forward_two_ordering_partition_csmooth")
greedy_backward_filter_csmooth <- ns_fn("greedy_backward_filter_csmooth")
initialize_csmoothEM <- ns_fn("initialize_csmoothEM")
init_two_trajectories <- ns_fn("init_two_trajectories")
parallel_initial_csmoothEM <- ns_fn("parallel_initial_csmoothEM")
optimize_initial_csmoothEM <- ns_fn("optimize_initial_csmoothEM")
do_csmoothEM <- ns_fn("do_csmoothEM")
do_csmoothEM_ml_collapsed <- ns_fn("do_csmoothEM_ml_collapsed")
do_csmoothEM_weighted <- ns_fn("do_csmoothEM_weighted")
